apiVersion: v1
kind: Service

metadata:
  name: frontend-service

spec:
  selector:
    app: frontend

  type: NodePort

  ports:
  - protocol: TCP
    port: 5173
    targetPort: 5173
    nodePort: 31546